# Generated by Django 4.2.3 on 2024-06-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check_IN_Date', models.DateField()),
                ('Check_out_Date', models.DateField()),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('Special_request', models.CharField(blank=True, max_length=150, null=True)),
                ('Check_IN_Time', models.TimeField()),
            ],
        ),
    ]
