# Generated by Django 5.0.4 on 2024-06-09 02:19
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),  # Correct dependency
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
