# Generated by Django 5.0.4 on 2024-06-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
