# Generated by Django 5.0.4 on 2024-06-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
